// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

// Begin prologue.
//
//
// End prologue.

#include <cassert>

namespace launcher
{
  namespace cli
  {
    // usage_para
    //
    inline usage_para::
    usage_para (value v)
    : v_ (v)
    {
    }

    // unknown_mode
    //
    inline unknown_mode::
    unknown_mode (value v)
    : v_ (v)
    {
    }

    // exception
    //
    inline ::std::ostream&
    operator<< (::std::ostream& os, const exception& e)
    {
      e.print (os);
      return os;
    }

    // unknown_option
    //
    inline unknown_option::
    unknown_option (const std::string& option)
    : option_ (option)
    {
    }

    inline const std::string& unknown_option::
    option () const
    {
      return option_;
    }

    // unknown_argument
    //
    inline unknown_argument::
    unknown_argument (const std::string& argument)
    : argument_ (argument)
    {
    }

    inline const std::string& unknown_argument::
    argument () const
    {
      return argument_;
    }

    // missing_value
    //
    inline missing_value::
    missing_value (const std::string& option)
    : option_ (option)
    {
    }

    inline const std::string& missing_value::
    option () const
    {
      return option_;
    }

    // invalid_value
    //
    inline invalid_value::
    invalid_value (const std::string& option,
                   const std::string& value,
                   const std::string& message)
    : option_ (option),
      value_ (value),
      message_ (message)
    {
    }

    inline const std::string& invalid_value::
    option () const
    {
      return option_;
    }

    inline const std::string& invalid_value::
    value () const
    {
      return value_;
    }

    inline const std::string& invalid_value::
    message () const
    {
      return message_;
    }

    // file_io_failure
    //
    inline file_io_failure::
    file_io_failure (const std::string& file)
    : file_ (file)
    {
    }

    inline const std::string& file_io_failure::
    file () const
    {
      return file_;
    }

    // unmatched_quote
    //
    inline unmatched_quote::
    unmatched_quote (const std::string& argument)
    : argument_ (argument)
    {
    }

    inline const std::string& unmatched_quote::
    argument () const
    {
      return argument_;
    }

    // argv_scanner
    //
    inline argv_scanner::
    argv_scanner (int& argc,
                  char** argv,
                  bool erase,
                  std::size_t sp)
    : start_position_ (sp + 1),
      i_ (1),
      argc_ (argc),
      argv_ (argv),
      erase_ (erase)
    {
    }

    inline argv_scanner::
    argv_scanner (int start,
                  int& argc,
                  char** argv,
                  bool erase,
                  std::size_t sp)
    : start_position_ (sp + static_cast<std::size_t> (start)),
      i_ (start),
      argc_ (argc),
      argv_ (argv),
      erase_ (erase)
    {
    }

    inline int argv_scanner::
    end () const
    {
      return i_;
    }

    // argv_file_scanner
    //
    inline argv_file_scanner::
    argv_file_scanner (int& argc,
                       char** argv,
                       const std::string& option,
                       bool erase,
                       std::size_t sp)
    : argv_scanner (argc, argv, erase, sp),
      option_ (option),
      options_ (&option_info_),
      options_count_ (1),
      i_ (1),
      skip_ (false)
    {
      option_info_.option = option_.c_str ();
      option_info_.search_func = 0;
    }

    inline argv_file_scanner::
    argv_file_scanner (int start,
                       int& argc,
                       char** argv,
                       const std::string& option,
                       bool erase,
                       std::size_t sp)
    : argv_scanner (start, argc, argv, erase, sp),
      option_ (option),
      options_ (&option_info_),
      options_count_ (1),
      i_ (1),
      skip_ (false)
    {
      option_info_.option = option_.c_str ();
      option_info_.search_func = 0;
    }

    inline argv_file_scanner::
    argv_file_scanner (const std::string& file,
                       const std::string& option,
                       std::size_t sp)
    : argv_scanner (0, zero_argc_, 0, sp),
      option_ (option),
      options_ (&option_info_),
      options_count_ (1),
      i_ (1),
      skip_ (false)
    {
      option_info_.option = option_.c_str ();
      option_info_.search_func = 0;

      load (file);
    }

    inline argv_file_scanner::
    argv_file_scanner (int& argc,
                       char** argv,
                       const option_info* options,
                       std::size_t options_count,
                       bool erase,
                       std::size_t sp)
    : argv_scanner (argc, argv, erase, sp),
      options_ (options),
      options_count_ (options_count),
      i_ (1),
      skip_ (false)
    {
    }

    inline argv_file_scanner::
    argv_file_scanner (int start,
                       int& argc,
                       char** argv,
                       const option_info* options,
                       std::size_t options_count,
                       bool erase,
                       std::size_t sp)
    : argv_scanner (start, argc, argv, erase, sp),
      options_ (options),
      options_count_ (options_count),
      i_ (1),
      skip_ (false)
    {
    }

    inline argv_file_scanner::
    argv_file_scanner (const std::string& file,
                       const option_info* options,
                       std::size_t options_count,
                       std::size_t sp)
    : argv_scanner (0, zero_argc_, 0, sp),
      options_ (options),
      options_count_ (options_count),
      i_ (1),
      skip_ (false)
    {
      load (file);
    }
  }
}

namespace launcher
{
  // options
  //

  inline const bool& options::
  help () const
  {
    return this->help_;
  }

  inline const bool& options::
  version () const
  {
    return this->version_;
  }

  inline const bool& options::
  build2_metadata () const
  {
    return this->build2_metadata_;
  }

  inline const bool& options::
  prerelease () const
  {
    return this->prerelease_;
  }

  inline const std::size_t& options::
  jobs () const
  {
    return this->jobs_;
  }

  inline bool options::
  jobs_specified () const
  {
    return this->jobs_specified_;
  }

  inline const std::string& options::
  game_exe () const
  {
    return this->game_exe_;
  }

  inline bool options::
  game_exe_specified () const
  {
    return this->game_exe_specified_;
  }

  inline const std::vector<std::string>& options::
  game_args () const
  {
    return this->game_args_;
  }

  inline bool options::
  game_args_specified () const
  {
    return this->game_args_specified_;
  }

  inline const bool& options::
  force_steam_runtime () const
  {
    return this->force_steam_runtime_;
  }

  inline const bool& options::
  no_self_update () const
  {
    return this->no_self_update_;
  }

  inline const bool& options::
  self_update_only () const
  {
    return this->self_update_only_;
  }

  inline const bool& options::
  skip_launch () const
  {
    return this->skip_launch_;
  }

  inline const bool& options::
  skip_remote () const
  {
    return this->skip_remote_;
  }

  inline const bool& options::
  install_game () const
  {
    return this->install_game_;
  }

  inline const bool& options::
  install_game_only () const
  {
    return this->install_game_only_;
  }

  inline const std::string& options::
  steam_user () const
  {
    return this->steam_user_;
  }

  inline bool options::
  steam_user_specified () const
  {
    return this->steam_user_specified_;
  }

  inline const bool& options::
  steam_qr () const
  {
    return this->steam_qr_;
  }

  inline const bool& options::
  steam_relogin () const
  {
    return this->steam_relogin_;
  }

  inline const bool& options::
  steam_forget () const
  {
    return this->steam_forget_;
  }

  inline const bool& options::
  steam_no_remember () const
  {
    return this->steam_no_remember_;
  }

  inline const bool& options::
  steam_reinstall () const
  {
    return this->steam_reinstall_;
  }

  inline const bool& options::
  steam_no_verify () const
  {
    return this->steam_no_verify_;
  }

  inline const std::uint32_t& options::
  steam_app_id () const
  {
    return this->steam_app_id_;
  }

  inline bool options::
  steam_app_id_specified () const
  {
    return this->steam_app_id_specified_;
  }

  inline const std::uint32_t& options::
  steam_depot_id () const
  {
    return this->steam_depot_id_;
  }

  inline bool options::
  steam_depot_id_specified () const
  {
    return this->steam_depot_id_specified_;
  }

  inline const std::uint64_t& options::
  steam_manifest_id () const
  {
    return this->steam_manifest_id_;
  }

  inline bool options::
  steam_manifest_id_specified () const
  {
    return this->steam_manifest_id_specified_;
  }

  inline const std::string& options::
  steam_branch () const
  {
    return this->steam_branch_;
  }

  inline bool options::
  steam_branch_specified () const
  {
    return this->steam_branch_specified_;
  }

  inline const std::uint32_t& options::
  steam_cell_id () const
  {
    return this->steam_cell_id_;
  }

  inline bool options::
  steam_cell_id_specified () const
  {
    return this->steam_cell_id_specified_;
  }

  inline const std::size_t& options::
  steam_chunk_jobs () const
  {
    return this->steam_chunk_jobs_;
  }

  inline bool options::
  steam_chunk_jobs_specified () const
  {
    return this->steam_chunk_jobs_specified_;
  }

  inline const std::string& options::
  proxy () const
  {
    return this->proxy_;
  }

  inline bool options::
  proxy_specified () const
  {
    return this->proxy_specified_;
  }
}

// Begin epilogue.
//
//
// End epilogue.
