// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef LAUNCHER_CACHE_CACHE_TYPES_ODB_HXX
#define LAUNCHER_CACHE_CACHE_TYPES_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include <launcher/cache/cache-types.hxx>

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // cached_file
  //
  template <>
  struct class_traits< ::launcher::cached_file >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::launcher::cached_file >
  {
    public:
    typedef ::launcher::cached_file object_type;
    typedef ::launcher::cached_file* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::std::string id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // component_version
  //
  template <>
  struct class_traits< ::launcher::component_version >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::launcher::component_version >
  {
    public:
    typedef ::launcher::component_version object_type;
    typedef ::launcher::component_version* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::launcher::component_type id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // cached_file
  //
  template <typename A>
  struct query_columns< ::launcher::cached_file, id_sqlite, A >
  {
    // path
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    path_type_;

    static const path_type_ path;

    // mtime
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::int64_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    mtime_type_;

    static const mtime_type_ mtime;

    // version
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    version_type_;

    static const version_type_ version;

    // component
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::launcher::component_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    component_type_;

    static const component_type_ component;

    // size
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint64_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    size_type_;

    static const size_type_ size;

    // hash
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    hash_type_;

    static const hash_type_ hash;
  };

  template <typename A>
  const typename query_columns< ::launcher::cached_file, id_sqlite, A >::path_type_
  query_columns< ::launcher::cached_file, id_sqlite, A >::
  path (A::table_name, "\"path\"", 0);

  template <typename A>
  const typename query_columns< ::launcher::cached_file, id_sqlite, A >::mtime_type_
  query_columns< ::launcher::cached_file, id_sqlite, A >::
  mtime (A::table_name, "\"mtime\"", 0);

  template <typename A>
  const typename query_columns< ::launcher::cached_file, id_sqlite, A >::version_type_
  query_columns< ::launcher::cached_file, id_sqlite, A >::
  version (A::table_name, "\"version\"", 0);

  template <typename A>
  const typename query_columns< ::launcher::cached_file, id_sqlite, A >::component_type_
  query_columns< ::launcher::cached_file, id_sqlite, A >::
  component (A::table_name, "\"component\"", 0);

  template <typename A>
  const typename query_columns< ::launcher::cached_file, id_sqlite, A >::size_type_
  query_columns< ::launcher::cached_file, id_sqlite, A >::
  size (A::table_name, "\"size\"", 0);

  template <typename A>
  const typename query_columns< ::launcher::cached_file, id_sqlite, A >::hash_type_
  query_columns< ::launcher::cached_file, id_sqlite, A >::
  hash (A::table_name, "\"hash\"", 0);

  template <typename A>
  struct pointer_query_columns< ::launcher::cached_file, id_sqlite, A >:
    query_columns< ::launcher::cached_file, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::launcher::cached_file, id_sqlite >:
    public access::object_traits< ::launcher::cached_file >
  {
    public:
    struct id_image_type
    {
      details::buffer id_value;
      std::size_t id_size;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // path_
      //
      details::buffer path_value;
      std::size_t path_size;
      bool path_null;

      // mtime_
      //
      long long mtime_value;
      bool mtime_null;

      // version_
      //
      details::buffer version_value;
      std::size_t version_size;
      bool version_null;

      // component_
      //
      long long component_value;
      bool component_null;

      // size_
      //
      long long size_value;
      bool size_null;

      // hash_
      //
      details::buffer hash_value;
      std::size_t hash_size;
      bool hash_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::launcher::cached_file, id_common >:
    public access::object_traits_impl< ::launcher::cached_file, id_sqlite >
  {
  };

  // component_version
  //
  template <typename A>
  struct query_columns< ::launcher::component_version, id_sqlite, A >
  {
    // component
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::launcher::component_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    component_type_;

    static const component_type_ component;

    // tag
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    tag_type_;

    static const tag_type_ tag;

    // installed_at
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::int64_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    installed_at_type_;

    static const installed_at_type_ installed_at;
  };

  template <typename A>
  const typename query_columns< ::launcher::component_version, id_sqlite, A >::component_type_
  query_columns< ::launcher::component_version, id_sqlite, A >::
  component (A::table_name, "\"component\"", 0);

  template <typename A>
  const typename query_columns< ::launcher::component_version, id_sqlite, A >::tag_type_
  query_columns< ::launcher::component_version, id_sqlite, A >::
  tag (A::table_name, "\"tag\"", 0);

  template <typename A>
  const typename query_columns< ::launcher::component_version, id_sqlite, A >::installed_at_type_
  query_columns< ::launcher::component_version, id_sqlite, A >::
  installed_at (A::table_name, "\"installed_at\"", 0);

  template <typename A>
  struct pointer_query_columns< ::launcher::component_version, id_sqlite, A >:
    query_columns< ::launcher::component_version, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::launcher::component_version, id_sqlite >:
    public access::object_traits< ::launcher::component_version >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // component_
      //
      long long component_value;
      bool component_null;

      // tag_
      //
      details::buffer tag_value;
      std::size_t tag_size;
      bool tag_null;

      // installed_at_
      //
      long long installed_at_value;
      bool installed_at_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 3UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::launcher::component_version, id_common >:
    public access::object_traits_impl< ::launcher::component_version, id_sqlite >
  {
  };

  // cached_file
  //
  // component_version
  //
}

#include <launcher/cache/cache-types-odb.ixx>

#include <odb/post.hxx>

#endif // LAUNCHER_CACHE_CACHE_TYPES_ODB_HXX
