name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  verify-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: cargo

      - name: Verify version is set
        run: |
          cargo install cargo-edit
          VERSION="${{ github.ref_name }}"
          cargo set-version ${VERSION#v}
          git diff-index --quiet HEAD --

  create-release:
    needs:
      - verify-package-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          body: |
            ## Installation instructions
            - [docs.iw4x.io/guides/install-windows](https://docs.iw4x.io/guides/install-windows)
            
            ## For support please visit the IW4x Discord
            - ### https://iw4x.io/discord
            
            ## You probably want to download [iw4x-launcher.exe](https://github.com/iw4x/launcher/releases/download/${{ github.ref_name }}/iw4x-launcher.exe)

  build-release-linux:
    needs:
      - verify-package-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            image: rust:latest
          - target: x86_64-unknown-linux-musl
            image: clux/muslrust:stable
    container: ${{ matrix.image }}
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run cargo build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: artifacts-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/iw4x-launcher
            target/${{ matrix.target }}/release/release-tool

  build-release-windows:
    needs:
      - verify-package-version
    runs-on: windows-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: i686-pc-windows-msvc

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run cargo build
        run: cargo build --release --target i686-pc-windows-msvc

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: artifacts-i686-pc-windows-msvc
          path: |
            target/i686-pc-windows-msvc/release/iw4x-launcher.exe
            target/i686-pc-windows-msvc/release/release-tool.exe

  release:
    needs:
      - create-release
      - build-release-linux
      - build-release-windows
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/download-artifact@v5
      - name: Create artifacts archives
        run: |
          7z a iw4x-launcher-x86_64-unknown-linux-gnu.tar ./artifacts-x86_64-unknown-linux-gnu/iw4x-launcher
          7z a iw4x-launcher-x86_64-unknown-linux-gnu.tar.gz ./iw4x-launcher-x86_64-unknown-linux-gnu.tar
          
          7z a iw4x-launcher-x86_64-unknown-linux-musl.tar ./artifacts-x86_64-unknown-linux-musl/iw4x-launcher
          7z a iw4x-launcher-x86_64-unknown-linux-musl.tar.gz ./iw4x-launcher-x86_64-unknown-linux-musl.tar
          
          7z a release-tool-x86_64-unknown-linux-gnu.tar ./artifacts-x86_64-unknown-linux-gnu/release-tool
          7z a release-tool-x86_64-unknown-linux-gnu.tar.gz ./release-tool-x86_64-unknown-linux-gnu.tar
          
          7z a release-tool-x86_64-unknown-linux-musl.tar ./artifacts-x86_64-unknown-linux-musl/release-tool
          7z a release-tool-x86_64-unknown-linux-musl.tar.gz ./release-tool-x86_64-unknown-linux-musl.tar
          
          7z a iw4x-launcher-i686-pc-windows-msvc.zip ./artifacts-i686-pc-windows-msvc/iw4x-launcher.exe
      - uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "*.tar.gz,*.zip,artifacts-i686-pc-windows-msvc/iw4x-launcher.exe"
          artifactErrorsFailBuild: true
          allowUpdates: true
          draft: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
